-- Net Parque - IOPT
-- Automatic code generated by IOPT2VHDL XSLT transformation.
-- by GRES Research Group - 2014 




  -- Component Definition:
  Component Parque IS
  Port(
      Clk : IN STD_LOGIC;
      PRES1_IN : IN STD_LOGIC;
      PRES2_IN : IN STD_LOGIC;
      TICKET_IN : IN STD_LOGIC;
      PRES1_OUT : IN STD_LOGIC;
      PRES2_OUT : IN STD_LOGIC;
      TICKET_OUT : IN STD_LOGIC;
      PRES1_IN_c : IN STD_LOGIC;
      PRES2_IN_c : IN STD_LOGIC;
      TICKET_IN_c : IN STD_LOGIC;
      PRES1_OUT_c : IN STD_LOGIC;
      PRES2_OUT_c : IN STD_LOGIC;
      TICKET_OUT_c : IN STD_LOGIC;
      AND_Y_up : IN STD_LOGIC;
      AND_X_up : IN STD_LOGIC;
      AND_X_down : IN STD_LOGIC;
      AND_Y_down : IN STD_LOGIC;
      CANC_IN : OUT STD_LOGIC;
      CANC_OUT : OUT STD_LOGIC;
      CANC_IN_c : OUT STD_LOGIC;
      CANC_OUT_c : OUT STD_LOGIC;
      occupied_1 : OUT INTEGER RANGE 0 TO 99;
      occupied_2 : OUT INTEGER RANGE 0 TO 99;
      Enable : IN STD_LOGIC;
      Reset : IN STD_LOGIC
  );
  End Component Parque;



    -- Port Map Template:
    U_Parque : Parque Port Map(
        Clk => clk,
        PRES1_IN => PRES1_IN,
        PRES2_IN => PRES2_IN,
        TICKET_IN => TICKET_IN,
        PRES1_OUT => PRES1_OUT,
        PRES2_OUT => PRES2_OUT,
        TICKET_OUT => TICKET_OUT,
        PRES1_IN_c => PRES1_IN_c,
        PRES2_IN_c => PRES2_IN_c,
        TICKET_IN_c => TICKET_IN_c,
        PRES1_OUT_c => PRES1_OUT_c,
        PRES2_OUT_c => PRES2_OUT_c,
        TICKET_OUT_c => TICKET_OUT_c,
        AND_Y_up => AND_Y_up,
        AND_X_up => AND_X_up,
        AND_X_down => AND_X_down,
        AND_Y_down => AND_Y_down,
        CANC_IN => CANC_IN,
        CANC_OUT => CANC_OUT,
        CANC_IN_c => CANC_IN_c,
        CANC_OUT_c => CANC_OUT_c,
        occupied_1 => occupied_1,
        occupied_2 => occupied_2,
        Enable => enable,
        Reset => reset
    );

